### Get all tasks list (Local) 
GET http://localhost:8080/tickets

### Get a single task (Local) 
GET http://localhost:8080/tickets/65c7050934136689422b0fc6

### Create a ticket (Local) 
POST http://localhost:8080/tickets HTTP/1.1 
Content-Type: application/json

{
  "title": "Login Page Error 2",
  "description": "Users unable to log in after recent update.",
  "assignee": "John Doe",
  "reporter": "Jane Smith",
  "priority": "High",
  "status": "Open",
  "createdDate": "2024-02-09T08:00:00.000Z",
  "lastUpdatedDate": "2024-02-09T10:30:00.000Z",
  "comments": "Investigating the root cause."
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////


### Get all tasks list (Local) 
GET http://localhost:8080/employees

### Get a single task (Local) 
GET http://localhost:8080/employees/65c72ae0d9440c5887d24d91

### Create an employee (Local) 
POST http://localhost:8080/employees HTTP/1.1 
Content-Type: application/json

{
  "username": "Robert",
  "email": "Smith",
  "password": "sweettooth"
}


